[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/r/:code"
  to = "/.netlify/functions/redirect/:code"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
